---

### APACHE2 VARS
'apache_ver': 'v24'

'modules': [ 
        "access_compat",
        "alias",
        "auth_basic",
        "authn_core",
        "authn_file",
        "authz_core",
        "authz_groupfile",
        "authz_host",
        "authz_user",
        "autoindex",
        "deflate",
        "dir",
        "env",
        "filter",
        "mime",
        "mpm_prefork",
        "negotiation",
        "rewrite",
        "setenvif",
        "socache_shmcb",
        "ssl",
        "status" ]


'module_configs': [
                    "alias",
                    "autoindex",
                    "deflate",
                    "dir",
                    "mime",
                    "mpm_prefork",
                    "negotiation",
                    "php5",
                    "setenvif",
                    "ssl",
                    "status"
                    ]


### PHPMYADMIN VARS
'apache_conf_path': '/etc/apache2/conf-enabled'

