---

- name: Add offical Nginx repos
  template: src={{ repo_file }} dest={{ repo_dest }}
  register: repo_added

- name: Import GPG signing key for Debian
  shell: 'curl http://nginx.org/packages/keys/nginx_signing.key | sudo apt-key add -'
  when: repo_added|changed and ansible_os_family == "Debian"


- name: Installing nginx packages - RedHat
  yum: name="nginx" state=present
  when: ansible_os_family == 'RedHat'

- name: Installing nginx packages - Debian
  apt: name="nginx" state=present update_cache=yes
  when: ansible_os_family == "Debian"


- name: Enable ports with iptables - RedHat 6
  command: "/sbin/iptables -I INPUT 2 -p tcp --dport {{ item }} -j ACCEPT"
  with_items: open_firewall_ports
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: Save default apache firewall rules - RedHat
  command: "/sbin/service iptables save"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: Setup default apache firewall rules - Debian
  command: ufw allow {{ item }}
  with_items: open_firewall_ports
  when: ansible_os_family == 'Debian'

- name: Setup default apache firewall rules - RedHat 7
  firewalld: port={{ item }}/tcp permanent=yes state=enabled
  with_items: open_firewall_ports
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Save default apache firewall rules - RedHat 7
  command: '/usr/bin/firewall-cmd --reload'
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
