---

- name: Installing php-fpm pkgs - RedHat
  yum: name={{ item }} state=present
  with_items: php_fpm_pkgs
  when: ansible_os_family == 'RedHat'

- name: Installing php-fpm pkgs - Debian
  apt: name={{ item }} state=present
  with_items:
    - php5-fpm
    - php-apc
  when: ansible_os_family == 'Debian'


- name: Setup www.conf pool
  template: src=www.conf.j2 dest="{{ php_fpm_path }}/www.conf" 
  notify: restart php-fpm

- name: create session path
  file: path={{ session_save_path }} owner={{ nginx_user }} group={{ nginx_user }} mode=0770 state=directory


- name: Start php-fpm and enable
  service: name="{{ php_fpm }}" state=started enabled=yes


