---
- hosts: all
  user: root

  tasks:
    - group_by: key={{ ansible_os_family }}
      tags: [ 'ius-repos', 'nginx', 'php5-fpm', 'php-fpm', 'mysql', 'holland' ]


### Applies only to RedHat systems

- hosts: RedHat
  user: root
  gather_facts: false

  pre_tasks:
    - name: install LSB_release req for RHEL systems
      yum: pkg=redhat-lsb state=installed
      register: installed
      tags: [ 'ius-repos', 'nginx', 'php-fpm', 'php5-fpm', 'mysql', 'holland' ]
    
    - name: regather facts
      setup: 
      when: installed|changed
      tags: [ 'ius-repos', 'nginx', 'php-fpm', 'php5-fpm', 'mysql', 'holland' ]

    - include_vars: group_vars/RHEL_7.yml
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
      tags: [ 'ius-repos', 'nginx', 'php-fpm', 'php5-fpm', 'mysql', 'holland' ]

  roles:
    - { role: IUS-repos, tags: [ ius-repos, php-fpm, php5-fpm, mysql ] }
    - { role: nginx, tags: nginx }
    - { role: php-fpm, tags: [ php-fpm, php5-fpm ] }
    - { role: mysql, tags: mysql }
    - { role: holland, tags: holland }


### Applies only to Debian systems

- hosts: Debian
  user: root
  gather_facts: false


  pre_tasks:
    - include_vars: group_vars/Ubuntu_14.yml
      when: ansible_os_family == 'Debian' and (ansible_distribution_version == '14.04' or ansible_distribution_version == '8')
      tags: [ 'ius-repos', 'nginx', 'php-fpm', 'php5-fpm', 'mysql', 'holland' ]

  roles:
    - { role: nginx, tags: nginx }
    - { role: php-fpm, tags: [ php-fpm, php5-fpm ] }
    - { role: mysql, tags: mysql }
    - { role: holland, tags: holland }

