---
- hosts: all
  user: root

  tasks:
    - group_by: key={{ ansible_os_family }}
      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]


### Applies only to RedHat systems

- hosts: RedHat
  user: root
  gather_facts: false

  pre_tasks:
    - include_vars: group_vars/RHEL_7.yml
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]

  roles:
    - { role: IUS-repos, tags: [ ius-repos, apache2, php5, mysql ] }
    - { role: apache2, tags: apache2 }
    - { role: php5, tags: php5 }
    - { role: mysql, tags: mysql }
    - { role: phpmyadmin, tags: phpmyadmin }
    - { role: holland, tags: holland }


### Applies only to Debian systems

- hosts: Debian
  user: root
  gather_facts: false


  pre_tasks:
    - include_vars: group_vars/Ubuntu_14.yml
      when: ansible_os_family == 'Debian' and (ansible_distribution_version == '14.04' or ansible_distribution_version == '8')
      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]

  roles:
    - { role: apache2, tags: apache2 }
    - { role: php5, tags: php5 }
    - { role: mysql, tags: mysql }
    - { role: phpmyadmin, tags: phpmyadmin }
    - { role: holland, tags: holland }

