---
# Generic Playbook to install and configure apache as an example
#
- name: Create vhosts directory
  file: path=/var/www/vhosts/ mode=0775 state=directory 

- name: Add default.template file 
  template: src=template.j2 dest={{ vhost_directory }}/default.template

- name: Add default Docroot
  file: dest='/var/www/html' state=directory owner={{ apache_user }} group={{ apache_user }}

- name: Set default vhost - Debian
  template: src="Debian/{{apache_ver}}/000-default.j2" dest="/etc/apache2/sites-available/000-default"
  when: ansible_os_family == 'Debian'
  notify: Restart apache

- name: Create domains document root
  file: path=/var/www/vhosts/{{ domain }} owner={{ apache_user }} group={{ apache_user }} mode=0775 state=directory
  when: domain != 'example.com'

- name: Add domains vhost file 
  template: src=vhost.j2 dest={{ vhost_directory }}/{{ domain }}.conf
  when: domain != 'example.com'
  notify: Restart apache

- name: Enable domain - Debian
  command: /usr/sbin/a2ensite {{ domain }}.conf
  when: ansible_os_family == 'Debian' and domain != 'example.com'
  notify: Restart apache

